// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Models;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20240712131151_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            Price = 60000m,
                            ProductName = "Iphone"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Price = 50000m,
                            ProductName = "Xiaomi"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = false,
                            Price = 40000m,
                            ProductName = "Samsung"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            Price = 30000m,
                            ProductName = "Huawei"
                        },
                        new
                        {
                            ProductId = 5,
                            IsActive = false,
                            Price = 20000m,
                            ProductName = "Lenovo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
